
name: macos_continuous

on:
  schedule:
    - cron: "10 * * * *"


jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "macos-latest"
    
    steps:
    - name: "checkout repo"
      uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: "Fetch tags"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            
            

    - name: "Fetch tag/branch history"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            git fetch --prune --unshallow
            
            

    - name: "Install Rust"
      uses: actions-rs/toolchain@dependabot/npm_and_yarn/actions/core-1.2.6
      with:
         profile: "minimal"
         toolchain: "stable"
         override: true
         components: "rustfmt"
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    - name: "Install System Deps"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            ./get-deps
            
            

    - name: "Build (Release mode)"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            cargo build --all --release
            
            

    - name: "Test (Release mode)"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            cargo test --all --release
            
            

    - name: "Package"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            export MACOSX_DEPLOYMENT_TARGET=10.9
            bash ci/deploy.sh
            
            

    - name: "Upload to Nightly Release"
      uses: wez/upload-release-assets@releases/v1
      with:
         files: "WezTerm-*.zip"
         release-tag: "nightly"
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
