
name: ubuntu18_continuous

on:
  schedule:
    - cron: "10 * * * *"


jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-18.04"
    
    steps:
    - name: "Update APT"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            sudo -n apt update
            

    - name: "Install git"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            sudo -n apt-get install -y git
            

    - name: "checkout repo"
      uses: actions/checkout@v2
      with:
         submodules: "recursive"
    - name: "Fetch tags"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            

    - name: "Fetch tag/branch history"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            git fetch --prune --unshallow
            

    - name: "Install Rust"
      uses: actions-rs/toolchain@dependabot/npm_and_yarn/actions/core-1.2.6
      with:
         profile: "minimal"
         toolchain: "stable"
         override: true
         components: "rustfmt"
    - name: "Cache cargo"
      uses: actions/cache@v2
      with:
         path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

         key: "ubuntu18-None-2-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
    - name: "Install System Deps"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            sudo -n ./get-deps
            

    - name: "Build (Release mode)"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            cargo build --all --release
            

    - name: "Test (Release mode)"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            cargo test --all --release
            

    - name: "Package"
      shell: bash
      run: |
            export BUILD_REASON=Schedule
            bash ci/deploy.sh
            

    - name: "Upload to Nightly Release"
      uses: wez/upload-release-assets@releases/v1
      with:
         files: "wezterm-*.deb;wezterm-*.xz;wezterm-*.tar.gz"
         release-tag: "nightly"
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
